pacman -S cbatticon
pacman -S cmatrix
pacman -S diodon
pacman -S discord
pacman -S fish
pacman -S git
pacman -S github-cli
pacman -S gparted
pacman -S grub-customizer
pacman -S grub-theme-cyberre
pacman -S hollywood
pacman -S htop
pacman -S kdeconnect
pacman -S kitty
pacman -S lightdm
pacman -S lightdm-gtk-greeter
pacman -S lightdm-gtk-greeter-settings
pacman -S lightdm-slick-greeter
pacman -S lightdm-webkit-theme-aether
pacman -S lightdm-webkit2-greeter
pacman -S lightdm-webkit2-theme-glorious
pacman -S lsd
pacman -S lxappearance
pacman -S neofetch
pacman -S neovim
pacman -S nerd-fonts-ubuntu-mono
pacman -S nerd-fonts-victor-mono
pacman -S network-manager-applet
pacman -S networkmanager
pacman -S nitrogen
pacman -S nodejs
pacman -S notepadqq
pacman -S notification-daemon
pacman -S noto-fonts
pacman -S npm
pacman -S papirus-icon-theme
pacman -S pavucontrol
pacman -S picom
pacman -S python-pip
pacman -S ranger
pacman -S rofi
pacman -S ubberband
pacman -S ruby
pacman -S snapd
pacman -S spotifyd
pacman -S sqlite
pacman -S starship
pacman -S telegram-desktop
pacman -S vlc
pacman -S volumeicon
pacman -S xclip
pacman -S yaourt
pacman -S yay
pacman -S zoom
pacman -S zsh
